# messages to broadcast
messages:
  - "&bMessage 1"
  - "&dMessage 2"
  - "&5Message 3"
  - "&9Message 4"

# Interval between Broadcasts In Seconds
interval: 120

# Play a sound when Broadcasting
sound: false