name: Auto Build

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle
        run: ./gradlew build

      - name: Automatic release
        uses: Trinovantes/action-automatic-releases@latest
        env:
          GITHUB_TOKEN: "${{ secrets.TOKEN }}"
        with:
          is_prerelease: false
          files: |
            *.jar
          auto_release_title: v1.1
          auto_release_tag: V1.1