name: Automatic Build

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.8

      - name: Build with Gradle
        run: |
          gradle --version
          gradle build

      - name: Automatic release
        uses: Trinovantes/action-automatic-release@master
        id: auto_release
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          is_prerelease: false
          auto_release_title: v1.1
          auto_release_tag: v1.1
      - name: Upload and build release
        uses: Trinovantes/action-release-upload@master
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          release_id: ${{ steps.auto_release.outputs.release_id }}
          upload_url: ${{ steps.auto_release.outputs.upload_url }}
          files: |-
            *.jar