name: Auto Build

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout resources
        uses: actions/checkout@v4
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build with Gradle
        uses: ./gradlew build
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            *.jar